# Generated by Django 4.1.2 on 2022-10-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.RemoveField(
            model_name="post",
            name="created",
        ),
        migrations.RemoveField(
            model_name="post",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated",
        ),
    ]
